### ISSUE TITLE
Can't start Ilastik simple_labeling example

### ISSUE THREAD

**Issue by rdemets** [ilastik/napari-ilastik#2]
Hi.

I am quite new to Napari and I've used Ilastik as a stand-alone software, but I wanted to try within the Napari N-dimensional environment.

I created an environment using the conda command : 
`conda create --yes --name napari-ilastik --strict-channel-priority --channel ilastik-forge --channel conda-forge --channel nodefaults 'python=3.7' fastfilters`

Then activated the environment and installed napari[all].
But when I tried to run the python code examples/simple_labeling.py, I got a KeyError : "Plugin 'napari_experimental_provide_dock_widget' does not provide any dock widgets"

I don't know if this comes from the newer Napari version or if I installed it wrongly. Please advice. Thank you very much.

-------

Traceback (most recent call last):
  File ".\examples\simple_labeling.py", line 23, in <module>
    main()
  File ".\examples\simple_labeling.py", line 18, in main
    viewer.window.add_plugin_dock_widget("napari_experimental_provide_dock_widget")
  File "D:\mbirdm\Napari\napari-ilastik\lib\site-packages\napari\_qt\qt_main_window.py", line 963, in add_plugin_dock_widget
    plugin_name, widget_name
  File "D:\mbirdm\Napari\napari-ilastik\lib\site-packages\napari\plugins\_plugin_manager.py", line 476, in get_widget
    raise KeyError(msg)
KeyError: "Plugin 'napari_experimental_provide_dock_widget' does not provide any dock widgets"

**Comment by emilmelnikov** [comment]
I think this is because you didn't install this plugin into the environment. If you ran  only `pip install napari[all]` without doing something like `pip install -e .`, you've only installed napari without the plugin itself, therefore, napari doesn't know where to look when the example script tries to add a dock widget.

Sorry for unclear installation instructions. I've updated the README, so there's hopefully less confusion now.

**Comment by emilmelnikov** [comment]
Did you download this plugin as a ZIP file? Currently you need to clone this repository via git and do everything from there:

```sh
git clone https://github.com/ilastik/napari-ilastik.git
```

Also, it seems that you didn't activate the conda environment (`conda activate napari-ilastik`). Be careful when running things like `pip install ...`. Usually you see the environment's name somewhere in your command prompt, but you can also double-check whether you've activated an environment or not by running `conda info`.

**Comment by rdemets** [comment]
Good call ! I used the ZIP instead of the git clone. Works well with git clone command. Thanks a lot  !
